spring:
  datasource:
    url: jdbc:mysql://localhost:3306/organization_db
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8083
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
